/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as Auth403RouteImport } from './routes/_auth/403'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as AuthEmbeddedNameRouteImport } from './routes/_auth/embedded/$name'
import { Route as AuthLogLoginRouteImport } from './routes/_auth/log/login'
import { Route as AuthLogOperaRouteImport } from './routes/_auth/log/opera'
import { Route as AuthMonitorOnlineRouteImport } from './routes/_auth/monitor/online'
import { Route as AuthMonitorRedisRouteImport } from './routes/_auth/monitor/redis'
import { Route as AuthMonitorServerRouteImport } from './routes/_auth/monitor/server'
import { Route as AuthPluginsConfigRouteImport } from './routes/_auth/plugins/config'
import { Route as AuthPluginsDictRouteImport } from './routes/_auth/plugins/dict'
import { Route as AuthPluginsNoticeRouteImport } from './routes/_auth/plugins/notice'
import { Route as AuthSandboxComponentsRouteImport } from './routes/_auth/sandbox/components'
import { Route as AuthSandboxQueryRouteImport } from './routes/_auth/sandbox/query'
import { Route as AuthSandboxTableRouteImport } from './routes/_auth/sandbox/table'
import { Route as AuthSchedulerManageRouteImport } from './routes/_auth/scheduler/manage'
import { Route as AuthSchedulerRecordRouteImport } from './routes/_auth/scheduler/record'
import { Route as AuthSystemDataPermissionRouteImport } from './routes/_auth/system/data-permission'
import { Route as AuthSystemDeptRouteImport } from './routes/_auth/system/dept'
import { Route as AuthSystemFileRouteImport } from './routes/_auth/system/file'
import { Route as AuthSystemMenuRouteImport } from './routes/_auth/system/menu'
import { Route as AuthSystemPluginRouteImport } from './routes/_auth/system/plugin'
import { Route as AuthSystemRoleRouteImport } from './routes/_auth/system/role'
import { Route as AuthSystemUserRouteImport } from './routes/_auth/system/user'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth403Route = Auth403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const AuthEmbeddedNameRoute = AuthEmbeddedNameRouteImport.update({
  id: '/embedded/$name',
  path: '/embedded/$name',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogLoginRoute = AuthLogLoginRouteImport.update({
  id: '/log/login',
  path: '/log/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogOperaRoute = AuthLogOperaRouteImport.update({
  id: '/log/opera',
  path: '/log/opera',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonitorOnlineRoute = AuthMonitorOnlineRouteImport.update({
  id: '/monitor/online',
  path: '/monitor/online',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonitorRedisRoute = AuthMonitorRedisRouteImport.update({
  id: '/monitor/redis',
  path: '/monitor/redis',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonitorServerRoute = AuthMonitorServerRouteImport.update({
  id: '/monitor/server',
  path: '/monitor/server',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPluginsConfigRoute = AuthPluginsConfigRouteImport.update({
  id: '/plugins/config',
  path: '/plugins/config',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPluginsDictRoute = AuthPluginsDictRouteImport.update({
  id: '/plugins/dict',
  path: '/plugins/dict',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPluginsNoticeRoute = AuthPluginsNoticeRouteImport.update({
  id: '/plugins/notice',
  path: '/plugins/notice',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSandboxComponentsRoute = AuthSandboxComponentsRouteImport.update({
  id: '/sandbox/components',
  path: '/sandbox/components',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSandboxQueryRoute = AuthSandboxQueryRouteImport.update({
  id: '/sandbox/query',
  path: '/sandbox/query',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSandboxTableRoute = AuthSandboxTableRouteImport.update({
  id: '/sandbox/table',
  path: '/sandbox/table',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerManageRoute = AuthSchedulerManageRouteImport.update({
  id: '/scheduler/manage',
  path: '/scheduler/manage',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerRecordRoute = AuthSchedulerRecordRouteImport.update({
  id: '/scheduler/record',
  path: '/scheduler/record',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemDataPermissionRoute =
  AuthSystemDataPermissionRouteImport.update({
    id: '/system/data-permission',
    path: '/system/data-permission',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSystemDeptRoute = AuthSystemDeptRouteImport.update({
  id: '/system/dept',
  path: '/system/dept',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemFileRoute = AuthSystemFileRouteImport.update({
  id: '/system/file',
  path: '/system/file',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemMenuRoute = AuthSystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemPluginRoute = AuthSystemPluginRouteImport.update({
  id: '/system/plugin',
  path: '/system/plugin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemRoleRoute = AuthSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemUserRoute = AuthSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof Auth403Route
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/sign-in': typeof GuestSignInRoute
  '/embedded/$name': typeof AuthEmbeddedNameRoute
  '/log/login': typeof AuthLogLoginRoute
  '/log/opera': typeof AuthLogOperaRoute
  '/monitor/online': typeof AuthMonitorOnlineRoute
  '/monitor/redis': typeof AuthMonitorRedisRoute
  '/monitor/server': typeof AuthMonitorServerRoute
  '/plugins/config': typeof AuthPluginsConfigRoute
  '/plugins/dict': typeof AuthPluginsDictRoute
  '/plugins/notice': typeof AuthPluginsNoticeRoute
  '/sandbox/components': typeof AuthSandboxComponentsRoute
  '/sandbox/query': typeof AuthSandboxQueryRoute
  '/sandbox/table': typeof AuthSandboxTableRoute
  '/scheduler/manage': typeof AuthSchedulerManageRoute
  '/scheduler/record': typeof AuthSchedulerRecordRoute
  '/system/data-permission': typeof AuthSystemDataPermissionRoute
  '/system/dept': typeof AuthSystemDeptRoute
  '/system/file': typeof AuthSystemFileRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/plugin': typeof AuthSystemPluginRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof Auth403Route
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/sign-in': typeof GuestSignInRoute
  '/embedded/$name': typeof AuthEmbeddedNameRoute
  '/log/login': typeof AuthLogLoginRoute
  '/log/opera': typeof AuthLogOperaRoute
  '/monitor/online': typeof AuthMonitorOnlineRoute
  '/monitor/redis': typeof AuthMonitorRedisRoute
  '/monitor/server': typeof AuthMonitorServerRoute
  '/plugins/config': typeof AuthPluginsConfigRoute
  '/plugins/dict': typeof AuthPluginsDictRoute
  '/plugins/notice': typeof AuthPluginsNoticeRoute
  '/sandbox/components': typeof AuthSandboxComponentsRoute
  '/sandbox/query': typeof AuthSandboxQueryRoute
  '/sandbox/table': typeof AuthSandboxTableRoute
  '/scheduler/manage': typeof AuthSchedulerManageRoute
  '/scheduler/record': typeof AuthSchedulerRecordRoute
  '/system/data-permission': typeof AuthSystemDataPermissionRoute
  '/system/dept': typeof AuthSystemDeptRoute
  '/system/file': typeof AuthSystemFileRoute
  '/system/menu': typeof AuthSystemMenuRoute
  '/system/plugin': typeof AuthSystemPluginRoute
  '/system/role': typeof AuthSystemRoleRoute
  '/system/user': typeof AuthSystemUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/403': typeof Auth403Route
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_auth/embedded/$name': typeof AuthEmbeddedNameRoute
  '/_auth/log/login': typeof AuthLogLoginRoute
  '/_auth/log/opera': typeof AuthLogOperaRoute
  '/_auth/monitor/online': typeof AuthMonitorOnlineRoute
  '/_auth/monitor/redis': typeof AuthMonitorRedisRoute
  '/_auth/monitor/server': typeof AuthMonitorServerRoute
  '/_auth/plugins/config': typeof AuthPluginsConfigRoute
  '/_auth/plugins/dict': typeof AuthPluginsDictRoute
  '/_auth/plugins/notice': typeof AuthPluginsNoticeRoute
  '/_auth/sandbox/components': typeof AuthSandboxComponentsRoute
  '/_auth/sandbox/query': typeof AuthSandboxQueryRoute
  '/_auth/sandbox/table': typeof AuthSandboxTableRoute
  '/_auth/scheduler/manage': typeof AuthSchedulerManageRoute
  '/_auth/scheduler/record': typeof AuthSchedulerRecordRoute
  '/_auth/system/data-permission': typeof AuthSystemDataPermissionRoute
  '/_auth/system/dept': typeof AuthSystemDeptRoute
  '/_auth/system/file': typeof AuthSystemFileRoute
  '/_auth/system/menu': typeof AuthSystemMenuRoute
  '/_auth/system/plugin': typeof AuthSystemPluginRoute
  '/_auth/system/role': typeof AuthSystemRoleRoute
  '/_auth/system/user': typeof AuthSystemUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/dashboard'
    | '/profile'
    | '/sign-in'
    | '/embedded/$name'
    | '/log/login'
    | '/log/opera'
    | '/monitor/online'
    | '/monitor/redis'
    | '/monitor/server'
    | '/plugins/config'
    | '/plugins/dict'
    | '/plugins/notice'
    | '/sandbox/components'
    | '/sandbox/query'
    | '/sandbox/table'
    | '/scheduler/manage'
    | '/scheduler/record'
    | '/system/data-permission'
    | '/system/dept'
    | '/system/file'
    | '/system/menu'
    | '/system/plugin'
    | '/system/role'
    | '/system/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/dashboard'
    | '/profile'
    | '/sign-in'
    | '/embedded/$name'
    | '/log/login'
    | '/log/opera'
    | '/monitor/online'
    | '/monitor/redis'
    | '/monitor/server'
    | '/plugins/config'
    | '/plugins/dict'
    | '/plugins/notice'
    | '/sandbox/components'
    | '/sandbox/query'
    | '/sandbox/table'
    | '/scheduler/manage'
    | '/scheduler/record'
    | '/system/data-permission'
    | '/system/dept'
    | '/system/file'
    | '/system/menu'
    | '/system/plugin'
    | '/system/role'
    | '/system/user'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/403'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_guest/sign-in'
    | '/_auth/embedded/$name'
    | '/_auth/log/login'
    | '/_auth/log/opera'
    | '/_auth/monitor/online'
    | '/_auth/monitor/redis'
    | '/_auth/monitor/server'
    | '/_auth/plugins/config'
    | '/_auth/plugins/dict'
    | '/_auth/plugins/notice'
    | '/_auth/sandbox/components'
    | '/_auth/sandbox/query'
    | '/_auth/sandbox/table'
    | '/_auth/scheduler/manage'
    | '/_auth/scheduler/record'
    | '/_auth/system/data-permission'
    | '/_auth/system/dept'
    | '/_auth/system/file'
    | '/_auth/system/menu'
    | '/_auth/system/plugin'
    | '/_auth/system/role'
    | '/_auth/system/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/403': {
      id: '/_auth/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Auth403RouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/embedded/$name': {
      id: '/_auth/embedded/$name'
      path: '/embedded/$name'
      fullPath: '/embedded/$name'
      preLoaderRoute: typeof AuthEmbeddedNameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/log/login': {
      id: '/_auth/log/login'
      path: '/log/login'
      fullPath: '/log/login'
      preLoaderRoute: typeof AuthLogLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/log/opera': {
      id: '/_auth/log/opera'
      path: '/log/opera'
      fullPath: '/log/opera'
      preLoaderRoute: typeof AuthLogOperaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitor/online': {
      id: '/_auth/monitor/online'
      path: '/monitor/online'
      fullPath: '/monitor/online'
      preLoaderRoute: typeof AuthMonitorOnlineRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitor/redis': {
      id: '/_auth/monitor/redis'
      path: '/monitor/redis'
      fullPath: '/monitor/redis'
      preLoaderRoute: typeof AuthMonitorRedisRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitor/server': {
      id: '/_auth/monitor/server'
      path: '/monitor/server'
      fullPath: '/monitor/server'
      preLoaderRoute: typeof AuthMonitorServerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plugins/config': {
      id: '/_auth/plugins/config'
      path: '/plugins/config'
      fullPath: '/plugins/config'
      preLoaderRoute: typeof AuthPluginsConfigRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plugins/dict': {
      id: '/_auth/plugins/dict'
      path: '/plugins/dict'
      fullPath: '/plugins/dict'
      preLoaderRoute: typeof AuthPluginsDictRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plugins/notice': {
      id: '/_auth/plugins/notice'
      path: '/plugins/notice'
      fullPath: '/plugins/notice'
      preLoaderRoute: typeof AuthPluginsNoticeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sandbox/components': {
      id: '/_auth/sandbox/components'
      path: '/sandbox/components'
      fullPath: '/sandbox/components'
      preLoaderRoute: typeof AuthSandboxComponentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sandbox/query': {
      id: '/_auth/sandbox/query'
      path: '/sandbox/query'
      fullPath: '/sandbox/query'
      preLoaderRoute: typeof AuthSandboxQueryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sandbox/table': {
      id: '/_auth/sandbox/table'
      path: '/sandbox/table'
      fullPath: '/sandbox/table'
      preLoaderRoute: typeof AuthSandboxTableRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/manage': {
      id: '/_auth/scheduler/manage'
      path: '/scheduler/manage'
      fullPath: '/scheduler/manage'
      preLoaderRoute: typeof AuthSchedulerManageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/record': {
      id: '/_auth/scheduler/record'
      path: '/scheduler/record'
      fullPath: '/scheduler/record'
      preLoaderRoute: typeof AuthSchedulerRecordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/data-permission': {
      id: '/_auth/system/data-permission'
      path: '/system/data-permission'
      fullPath: '/system/data-permission'
      preLoaderRoute: typeof AuthSystemDataPermissionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/dept': {
      id: '/_auth/system/dept'
      path: '/system/dept'
      fullPath: '/system/dept'
      preLoaderRoute: typeof AuthSystemDeptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/file': {
      id: '/_auth/system/file'
      path: '/system/file'
      fullPath: '/system/file'
      preLoaderRoute: typeof AuthSystemFileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/menu': {
      id: '/_auth/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof AuthSystemMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/plugin': {
      id: '/_auth/system/plugin'
      path: '/system/plugin'
      fullPath: '/system/plugin'
      preLoaderRoute: typeof AuthSystemPluginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/role': {
      id: '/_auth/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthSystemRoleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system/user': {
      id: '/_auth/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof AuthSystemUserRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  Auth403Route: typeof Auth403Route
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthEmbeddedNameRoute: typeof AuthEmbeddedNameRoute
  AuthLogLoginRoute: typeof AuthLogLoginRoute
  AuthLogOperaRoute: typeof AuthLogOperaRoute
  AuthMonitorOnlineRoute: typeof AuthMonitorOnlineRoute
  AuthMonitorRedisRoute: typeof AuthMonitorRedisRoute
  AuthMonitorServerRoute: typeof AuthMonitorServerRoute
  AuthPluginsConfigRoute: typeof AuthPluginsConfigRoute
  AuthPluginsDictRoute: typeof AuthPluginsDictRoute
  AuthPluginsNoticeRoute: typeof AuthPluginsNoticeRoute
  AuthSandboxComponentsRoute: typeof AuthSandboxComponentsRoute
  AuthSandboxQueryRoute: typeof AuthSandboxQueryRoute
  AuthSandboxTableRoute: typeof AuthSandboxTableRoute
  AuthSchedulerManageRoute: typeof AuthSchedulerManageRoute
  AuthSchedulerRecordRoute: typeof AuthSchedulerRecordRoute
  AuthSystemDataPermissionRoute: typeof AuthSystemDataPermissionRoute
  AuthSystemDeptRoute: typeof AuthSystemDeptRoute
  AuthSystemFileRoute: typeof AuthSystemFileRoute
  AuthSystemMenuRoute: typeof AuthSystemMenuRoute
  AuthSystemPluginRoute: typeof AuthSystemPluginRoute
  AuthSystemRoleRoute: typeof AuthSystemRoleRoute
  AuthSystemUserRoute: typeof AuthSystemUserRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth403Route: Auth403Route,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthEmbeddedNameRoute: AuthEmbeddedNameRoute,
  AuthLogLoginRoute: AuthLogLoginRoute,
  AuthLogOperaRoute: AuthLogOperaRoute,
  AuthMonitorOnlineRoute: AuthMonitorOnlineRoute,
  AuthMonitorRedisRoute: AuthMonitorRedisRoute,
  AuthMonitorServerRoute: AuthMonitorServerRoute,
  AuthPluginsConfigRoute: AuthPluginsConfigRoute,
  AuthPluginsDictRoute: AuthPluginsDictRoute,
  AuthPluginsNoticeRoute: AuthPluginsNoticeRoute,
  AuthSandboxComponentsRoute: AuthSandboxComponentsRoute,
  AuthSandboxQueryRoute: AuthSandboxQueryRoute,
  AuthSandboxTableRoute: AuthSandboxTableRoute,
  AuthSchedulerManageRoute: AuthSchedulerManageRoute,
  AuthSchedulerRecordRoute: AuthSchedulerRecordRoute,
  AuthSystemDataPermissionRoute: AuthSystemDataPermissionRoute,
  AuthSystemDeptRoute: AuthSystemDeptRoute,
  AuthSystemFileRoute: AuthSystemFileRoute,
  AuthSystemMenuRoute: AuthSystemMenuRoute,
  AuthSystemPluginRoute: AuthSystemPluginRoute,
  AuthSystemRoleRoute: AuthSystemRoleRoute,
  AuthSystemUserRoute: AuthSystemUserRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestSignInRoute: typeof GuestSignInRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSignInRoute: GuestSignInRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
