"""新增 sys_notification / sys_notification_read

Revision ID: 9609aedfaf8d
Revises: d0000000usertz
Create Date: 2026-08-30 16:57:30.201966+08:00

"""

import sqlalchemy as sa

from alembic import op

import backend.common.model

# revision identifiers, used by Alembic.
revision = '9609aedfaf8d'
down_revision = 'd0000000usertz'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sys_notification',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花算法主键 ID'),
        sa.Column('title', backend.common.model.UniversalStr(length=128), nullable=False, comment='标题'),
        sa.Column('content', backend.common.model.UniversalText(), nullable=False, comment='内容'),
        sa.Column('category', sa.Integer(), nullable=False, comment='分类（0：系统、1：公告、2：任务事件）'),
        sa.Column(
            'link',
            backend.common.model.UniversalStr(length=256),
            nullable=True,
            comment='点击跳转的前端路由，为空则不可点',
        ),
        sa.Column('recipient_id', sa.BigInteger(), nullable=True, comment='接收人 ID（为空表示全员广播）'),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.Column(
            'deleted', sa.BigInteger(), server_default='0', nullable=False, comment='是否已删除（0：否；id：是）'
        ),
        sa.Column('deleted_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='删除时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='站内通知表',
    )
    op.create_index(op.f('ix_sys_notification_id'), 'sys_notification', ['id'], unique=True)
    op.create_index(op.f('ix_sys_notification_recipient_id'), 'sys_notification', ['recipient_id'], unique=False)
    op.create_table(
        'sys_notification_read',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花算法主键 ID'),
        sa.Column('notification_id', sa.BigInteger(), nullable=False, comment='通知 ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
        sa.Column('read_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='阅读时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_read'),
        comment='站内通知已读标记表',
    )
    op.create_index(op.f('ix_sys_notification_read_id'), 'sys_notification_read', ['id'], unique=True)
    op.create_index(
        op.f('ix_sys_notification_read_notification_id'), 'sys_notification_read', ['notification_id'], unique=False
    )
    op.create_index(op.f('ix_sys_notification_read_user_id'), 'sys_notification_read', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_notification_read_user_id'), table_name='sys_notification_read')
    op.drop_index(op.f('ix_sys_notification_read_notification_id'), table_name='sys_notification_read')
    op.drop_index(op.f('ix_sys_notification_read_id'), table_name='sys_notification_read')
    op.drop_table('sys_notification_read')
    op.drop_index(op.f('ix_sys_notification_recipient_id'), table_name='sys_notification')
    op.drop_index(op.f('ix_sys_notification_id'), table_name='sys_notification')
    op.drop_table('sys_notification')
    # ### end Alembic commands ###
