"""同步列注释 —— 模型里改过、库上没跟

这 16 处是历史遗留：模型里的 `comment=` 改过（比如 `sys_file.path` 从
「相对 UPLOAD_DIR 的存储路径」改成「相对落盘根目录的存储路径」），但库上是
`create_all` 一次性建的，之后没人同步。**没有任何功能影响**——列注释只在
DBA 工具和 `sp_help` 里能看到。

单独拆出来而不是混进基线：基线要保持为空（它只是个起点标记），
而这一份是真实的一次结构变更，应该有自己的记录。

Revision ID: f532e6110c78
Revises:
Create Date: 2026-08-22 18:30:43.003028+08:00

"""
import contextlib

import sqlalchemy as sa
import sqlalchemy.exc

from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c0000000comments'
down_revision = 'b0000000baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    🔴 **这一份必须幂等。** 同一份迁移在两种库上遇到的状态不一样：

    - **老库**（2026-08-22 之前 create_all 建的）：列注释是旧的 → 要改
    - **新建库**（现在 create_all 一建就是新注释，比如刚跑过 `pnpm --filter api test:db`
      的 fba_test）：列注释**已经是目标值** → 再执行会炸

    炸的样子：`sp_addextendedproperty` 报
    `Property 'MS_Description' already exists for 'dbo.sys_dept.code'`。
    alembic 的 `alter_column(comment=...)` 在 mssql 上编译成 add 而不是 update，
    所以「已经对了」反而失败。

    这不是这一份的特例 —— **凡是「补齐历史遗留」类的迁移都有这个形状**：
    新建的库天然就是目标状态。写这类迁移时先问「新库跑这一步会怎样」。

    ⚠️ 只吞 `ProgrammingError`（"already exists" 属于它），不吞所有异常 ——
    连接断了、权限不足也是异常，那些必须让迁移失败。实测 SQL Server 在这里
    不会毒化事务，后续语句照常执行。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_dept', 'code',
                   existing_type=sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='部门编码',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_file', 'path',
                   existing_type=sa.NVARCHAR(length=512, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='相对落盘根目录的存储路径',
                   existing_comment='相对 UPLOAD_DIR 的存储路径',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_file', 'is_public',
                   existing_type=mssql.BIT(),
                   server_default=None,
                   comment='是否落在公开子树（不鉴权可读）',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'request_headers',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='请求头（已脱敏）',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'response_headers',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='响应头',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'response_body',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='响应体（超限截断）',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_role', 'code',
                   existing_type=sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='角色编码',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_user', 'timezone',
                   existing_type=sa.NVARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'),
                   server_default=None,
                   comment='显示时区(IANA 标识)',
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_user', 'timezone',
                   existing_type=sa.NVARCHAR(length=64, collation='SQL_Latin1_General_CP1_CI_AS'),
                   server_default=sa.text("('Asia/Shanghai')"),
                   comment=None,
                   existing_comment='显示时区(IANA 标识)',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_role', 'code',
                   existing_type=sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment=None,
                   existing_comment='角色编码',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'response_body',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment=None,
                   existing_comment='响应体（超限截断）',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'response_headers',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment=None,
                   existing_comment='响应头',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_opera_log', 'request_headers',
                   existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment=None,
                   existing_comment='请求头（已脱敏）',
                   existing_nullable=True)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_file', 'is_public',
                   existing_type=mssql.BIT(),
                   server_default=sa.text('((0))'),
                   comment=None,
                   existing_comment='是否落在公开子树（不鉴权可读）',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_file', 'path',
                   existing_type=sa.NVARCHAR(length=512, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment='相对 UPLOAD_DIR 的存储路径',
                   existing_comment='相对落盘根目录的存储路径',
                   existing_nullable=False)
    with contextlib.suppress(sqlalchemy.exc.ProgrammingError):
        op.alter_column('sys_dept', 'code',
                   existing_type=sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
                   comment=None,
                   existing_comment='部门编码',
                   existing_nullable=False)
    # ### end Alembic commands ###
